#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Write your code here
    height = 0
    count = 0
    i = 0
    new = []
    for x in range(steps):
        if path[x] == 'U':
            new.append(1)
        else:
            new.append(-1)
    for x in range(steps):
        height+= new[x]
        if height == 0:
            if new[i] == -1:
                count += 1
            i = x+1
    return count    
        
            
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')
