#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    value = arr[-1]
    j=1


    n= n - 1
    while True:

        if value < arr[n-j]:
            if n == j:
                arr[n-j+1] = arr[n-j]
                for x in arr:
                    print(x,end=' ')
                print()
                
                arr[n-j+1] = arr[n-j]
                arr[0] = value
                for x in arr:
                    print(x,end=' ')
                print()
              
               

                
                
                
                
               

                break
            arr[n-j+1] = arr[n-j]
            for x in arr:
                print(x,end=' ')
            print()
            j += 1





        else:
            arr[n-j+1] = value
            for x in arr:
                print(x,end=' ')
            break

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
